sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        animation.runImageAnimation(
        Quester,
        [img`
            ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff..........
            .ffefbf44fbfeff.........
            .fee41fddf14eef.........
            fdfeeddddd4eff..........
            fbffee444edd4e..........
            fbf4f2222edde...........
            fcf.f22cccee............
            .ff.f44cdc4f............
            ....fffddcff............
            .....fddcff.............
            ....cddc................
            ....cdc.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            ..feeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            fdfefbf44fbfeff.........
            fbfe41fddf14ef..........
            fbffe4dddd4efe..........
            fcfef22222f4e...........
            .ff4f44554f4e...........
            ....ffffffdde...........
            .....ffffedde...........
            ..........ee............
            .........ccc............
            ........cc1cc...........
            .........c1c............
            .........c1c............
            .........c1c............
            .........c1c............
            `,img`
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        500,
        false
        )
    } else {
    	
    }
})
let Quester: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
Quester = sprites.create(img`
    . . . . . . c c c c . . . . . . 
    . . . . c c c 4 4 c c c . . . . 
    . . . c c c 4 4 4 4 c c c . . . 
    . . c c c f f f f f f c c c . . 
    . . c c f 4 4 4 4 4 4 f f c . . 
    . . c f 4 c c c c c c 4 f c . . 
    . . c c c c f d d f c c c c . . 
    . c c f c b 6 d d 6 b c f c c . 
    . c f f d 1 6 d d 6 1 d f f c . 
    . . c f f d d d d d d f f c . . 
    . . . c f f d d d d f f c . . . 
    . . 4 4 c 1 4 f f 4 1 c 4 4 . . 
    . . d d c 4 f 4 4 f 4 c d d . . 
    . . d d c e e 5 5 e e c d d . . 
    . . . . . c c c c c c . . . . . 
    . . . . . c c . . c c . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Quester)
scene.cameraFollowSprite(Quester)
let mySprite = sprites.create(img`
    . . . . 4 4 1 1 1 4 4 . . . . . 
    . . . . 4 4 1 f 1 4 4 . . . . . 
    e e e . 4 4 1 1 1 4 4 . . . . . 
    e e e . 4 1 4 4 4 1 4 . . . . . 
    e e e . 4 f f f f f 4 . . . . . 
    e e e . 4 4 4 4 4 4 4 . . . . . 
    e e e f f f f f f f f f . . . . 
    4 e f f f f f f f f f f f 4 . . 
    4 e f f f f f f f f f f f 4 . . 
    e e e f f f f f f f f f . . . . 
    e e e f 5 f 5 f 5 f 5 f . . . . 
    . . . f 5 f 5 f 5 f 5 f . . . . 
    . . . f 5 5 5 5 5 5 5 f . . . . 
    . . . f f f f f f f f f . . . . 
    . . . f f f f f f f f f . . . . 
    . . . 4 4 . . . . . 4 4 . . . . 
    `, SpriteKind.Enemy)
mySprite.setPosition(randint(5, 19), randint(5, 19))
